### ISSUE TITLE
Gradle command line does not work on Windows

### ISSUE THREAD

**Issue by StefanLobbenmeier** [dasniko/nashorn-spock-jasmine#1]
In the build.gradle you call npm like this:
https://github.com/dasniko/nashorn-spock-jasmine/blob/1f86561d150a72fe0b9d29563849a3d24c6e718d/build.gradle#L26

On windows, this will cause an error that npm could not be found. Instead, this works:
    `commandLine = ["cmd", "/c", "npm", "install"]`

**Comment by dasniko** [comment]
Thanks for the comment.
This is a fairly old repo and I won't do any updates to this.
